# Synapse SSDT Build job
# Further reading is available in the documentation
# https://docs.microsoft.com/en-gb/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-continuous-integration-and-deployment#continuous-deployment-with-the-azure-synapse-analytics-or-database-deployment-task

parameters:
  - name: doPublish
    default: false
    type: boolean

jobs:
- job: "Build_SynapseDacPac"
  pool:
    vmImage: 'windows-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  - task: CopyFiles@2
    condition: and(succeeded(), eq('${{ parameters.doPublish }}', true))
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(agent.builddirectory)'
      TargetFolder: '$(build.artifactstagingdirectory)'
      Contents: '**\synapse\**'
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq('${{ parameters.doPublish }}', true)) 
    displayName: 'Publish Artifact: SynapseDacPac'
    inputs:
      targetPath: '$(build.artifactstagingdirectory)'
      artifact: 'SynapseDacPac'
      publishLocation: 'pipeline'
