# Synapse SSDT Deploy Job
# Further reading is available in the documentation
# https://docs.microsoft.com/en-gb/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-continuous-integration-and-deployment#continuous-deployment-with-the-azure-synapse-analytics-or-database-deployment-task

jobs:
- job: "Deploy_Synapse"
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific'
      project: '$(project)'
      artifact: 'SynapseDacPac'
      pipeline: '$(pipelineId)'
      runVersion: 'latest'
      path: $(System.DefaultWorkingDirectory)\SynapseDacPac
  - task: SqlAzureDacpacDeployment@1
    displayName: 'Azure SQL DacpacTask'
    inputs:
      azureSubscription: '$(svc_conn)'
      AuthenticationType: connectionString
      ConnectionString: '$(sqlpoolconn)'
      DacpacFile: '$(System.DefaultWorkingDirectory)\workloadsyndemo\bin\Release\workloadsyndemo.dacpac'