trigger: 
- main

jobs:
- job: "Build_ADFARMTemplates"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: templates/adf_ci.yaml
  # Publish the Artifact to be used as a source for a release pipeline
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/ArmTemplate'
      artifact: 'AdfArmTemplates'
      publishLocation: 'pipeline'

- job: "Build_SynapseDacPac"
  pool:
    vmImage: 'windows-latest'
  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
  steps:
  - template: templates/synapse_ci.yaml
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(agent.builddirectory)'
      TargetFolder: '$(build.artifactstagingdirectory)'
      Contents: '**\synapse\**'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: SynapseDacPac'
    inputs:
      targetPath: '$(build.artifactstagingdirectory)'
      artifact: 'SynapseDacPac'
      publishLocation: 'pipeline'
