trigger: 
- main

jobs:
- template: templates/adf_ci.yaml
    # Publish the Artifact to be used as a source for a release pipeline
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.Repository.LocalPath)/ArmTemplate'
    artifact: 'AdfArmTemplates'
    publishLocation: 'pipeline'
# - template: templates/synapse_ci.yaml
