resources:
  pipelines:
  - pipeline: mdwreleasepipeline   # Name of the pipeline resource
    source: mdw-adf-ci # Name of the pipeline referenced by the pipeline resource
    trigger: 
      branches:
      - main

jobs:
- template: templates/adf_cd.yaml
- template: templates/synapse_cd.yaml

