<<<<<<< HEAD
trigger: none

resources:
  pipelines:
  - pipeline: 'mdw-cd'   # Name of the pipeline resource
    source: 'mdw-ci' # Name of the pipeline referenced by the pipeline resource
    trigger: 
      branches:
      - main

=======
 # Trigger on main branch changes
trigger: 
  branches:
  - main
  
>>>>>>> update trigger
jobs:
- template: templates/adf_cd.yaml
- template: templates/synapse_cd.yaml

