trigger:
  branches:
    - main
paths:
    include:
      - adf/*
      - synapse/*
      
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- template: templates/adf_ci.yaml
- template: templates/synapse_ci.yaml



