trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: "BuildSynapseDacPac"
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(agent.builddirectory)'
      TargetFolder: '$(build.artifactstagingdirectory)'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: drop'
    inputs:
      targetPath: '$(build.artifactstagingdirectory)'
      artifact: SynapseDacPac
      publishLocation: 'pipeline'

- job: "BuildAdfArmTemplate"
  pool:
    vmImage: ubuntu-default
  steps:
  # Installs Node and the npm packages saved in your package.json file in the build
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - task: Npm@1
    inputs:
      command: 'install'
      verbose: true
    displayName: 'Install npm package'
  # Validates all of the ADF resources in the repository. You will get the same validation errors as when "Validate All" is clicked
  # Enter the appropriate subscription and name for the source factory 
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build validate $(Build.Repository.LocalPath)/adf /subscriptions/$(subscriptionid)/resourceGroups/testResourceGroup/providers/Microsoft.DataFactory/factories/$(adfname)'
    displayName: 'Validate'
  # Validate and then generate the ARM template into the destination folder. Same as clicking "Publish" from UX
  # The ARM template generated is not published to the ‘Live’ version of the factory. Deployment should be done using a CI/CD pipeline. 
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build export $(Build.Repository.LocalPath)/adf /subscriptions/$(subscriptionid)/resourceGroups/testResourceGroup/providers/Microsoft.DataFactory/factories/$(adfname) "ArmTemplate"'
    displayName: 'Validate and Generate ARM template'
  # Publish the Artifact to be used as a source for a release pipeline
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/ArmTemplate'
      artifact: 'AdfArmTemplates'
      publishLocation: 'pipeline'